apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  {{- if .Values.app.iam }}
    eks.amazonaws.com/role-arn: {{ .Values.app.iam | quote }}
  {{- end }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}